#!/usr/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: $0 <file>"
	exit 1
fi

FILE="$1"

while read -r NUMBER; do
	factors=$(factor "$NUMBER" | sed 's/^[0-9]*://')

	p=$(echo "$factors" | awk '{print $1}')
	q=$(echo "$factors" | awk '{print $2}')

	echo "$NUMBER=$p*$q"
done < "$FILE"
