#!/usr/bin/python3

import time
import math
import sys

def factorize(n):
    factors = []

    while n % 2 == 0:
        factors.append(2)
        n //= 2

    for i in range(3, int(math.sqrt(n)) + 1, 2):
         while n % i == 0:
             factors.append(i)
             n //= i

    if n > 2:
        factors.append(n)
    return factors

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <number>")
        sys.exit(1)

    n = int(sys.argv[1])
    factors = factorize(n)
    print(f"{n}={'*'.join(map(str, factors))}")
